### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by hassanfaroooq** [johfer/node-red-contrib-interpolate#1]
please give me example with picture  I am new to node-red

**Comment by johfer** [comment]
ok, will do later today

**Comment by johfer** [comment]
This is the flow representing the example from the README:

![image](https://user-images.githubusercontent.com/2000667/60747676-37f95800-9f87-11e9-8ca3-2705ce91d8ae.png)

As JSON:
`[{"id":"b203c324.00663","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"360edb38.d012f4","type":"interpolate","z":"b203c324.00663","name":"","storename":"","x":670,"y":160,"wires":[["6d705fc8.a76c1"]]},{"id":"85872d2b.321c9","type":"change","z":"b203c324.00663","name":"datagrid topic","rules":[{"t":"set","p":"topic","pt":"msg","to":"datagrid","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":440,"y":120,"wires":[["360edb38.d012f4"]]},{"id":"6da2f448.1a4bdc","type":"inject","z":"b203c324.00663","name":"inject grid","topic":"","payload":"{\"x\":[0.1,0.2,0.5,1,2.1,10,100],\"y\":[23,22.9,22.7,22.5,22,21,19]}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":120,"wires":[["85872d2b.321c9"]]},{"id":"527f01dd.d6237","type":"inject","z":"b203c324.00663","name":"inject value","topic":"","payload":"{\"x\":42}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":440,"y":200,"wires":[["360edb38.d012f4"]]},{"id":"6d705fc8.a76c1","type":"debug","z":"b203c324.00663","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":870,"y":160,"wires":[]}]`

**Comment by hassanfaroooq** [comment]
thanks a lot sir
